name: Build LaTeX document

on:
  push:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v4

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v3
        with:
          root_files: main.tex
          latexmk_use_lualatex: false
          latexmk_shell_escape: false

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: main.pdf
